#!/usr/bin/env bash

echo "Agentic Engineering Team"
echo ""
echo "This repo demonstrates a small engineering team with explicit roles:"
echo "  - Architect"
echo "  - Implementer"
echo "  - Reviewer"
echo "  - Tester"
echo "  - Orchestrator"
echo ""
echo "Worked example:"
echo "  Express middleware with rate limiting, request validation, and auth."
echo ""
echo "Run:"
echo "  npm install"
echo "  npm start"
echo ""
echo "Then inspect:"
echo "  - AGENT_LOG.md"
echo "  - BUILD_MANIFEST.json"
echo "  - DEPLOYED_ARCHITECTURE.md"
echo "  - artifacts/review_report.md"
echo "  - artifacts/test_report.md"
